name: AeroVision
channels:
  - open3d-admin
  - https://conda.anaconda.org/conda-forge/
  - defaults
  - pytorch
  - comet_ml
dependencies:
  - python==3.8.6
  - numpy
  - pytorch-lightning==1.0.5
  - matplotlib
  - opencv
  - pyvista
  - h5py
  - scipy
  - scikit-learn
  - open3d
  - smbus2
  - addict
  - pandas
  - plyfile
  - pytorch=1.7.0
  - torchvision=0.8.1
  - cudatoolkit=10.2
  - scikit-image
  - comet_ml

