name: /home/alex/miniconda3/envs
channels:
  - open3d-admin
  - https://conda.anaconda.org/conda-forge/
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pytorch-lightning==1.0.5
  - matplotlib
  - opencv
  - pyvista
  - h5py
  - scipy
  - scikit-learn
  - open3d
  - smbus2
  - addict
  - pandas
  - plyfile
  - torchvision>=0.8
  - pytorch==1.5.0
  - scikit-image

