language: python
dist: xenial
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "3.9-dev"
install:
  - pip install coverage
  - pip install coveralls
script:
  - coverage run test.py
after_success:
  - coveralls
