# Messages to server
# Successfully connected to ...
# Failed to connect to ...
# ... began recording
# ... finished recording, ... file created
#  ... started sending file ... to server
# file ... from ... saved as ...
# begin unifying? yes/no
# unified file saved as ...